name: clean_up
description: "A new Flutter project."

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#--------------- PACKAGES -----------------#

dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  #Map
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  geolocator: ^10.1.1

  #Payment


  #Supabase
  supabase_flutter: ^2.8.0

  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.14
  flutter_local_notifications: ^18.0.0
  socket_io_client: ^3.0.1
  sliding_sheet2: ^2.0.1
  stop_watch_timer: ^3.2.1
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.2.1
  lottie: ^3.1.3
  connectivity_plus: ^5.0.2
  awesome_snackbar_content: ^0.1.4
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  googleapis_auth: ^1.6.0







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/on_boarding_images/onBoarding1.png
    - assets/images/on_boarding_images/onBoarding2.png
    - assets/images/on_boarding_images/onBoarding3.png
    - assets/images/animations/verify.webp
    - assets/images/animations/success.webp
    - assets/images/avatar/defaultUser.png
    - assets/images/services/1.png
    - assets/images/services/2.png
    - assets/images/services/3.png
    - assets/logo/PNG 2.png
    - assets/logo/PNG 1.png
    - assets/images/avatar/avatar.png
    - assets/images/animations/LottieAnimation.json
    - .env
    - assets/images/animations/success.json
    - assets/service_account/service_account.json
    - assets/clean-up-39d88-f075a7156ffb.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
