name: clean_up
description: "A new Flutter project."

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#--------------- PACKAGES -----------------#

dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  #Map
  geolocator: ^13.0.1
  flutter_map: ^7.0.2

  #Payment
  flutter_stripe: ^11.2.0

  #Supabase
  supabase_flutter: ^2.8.0

  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.14
  flutter_local_notifications: ^18.0.0
  socket_io_client: ^3.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
   - assets/images/on_boarding_images/onBording1.png
   - assets/images/on_boarding_images/onBording2.png
   - assets/images/on_boarding_images/onBording3.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
